Account:
  - accounts/**/*
Admin:
  - admin/**/*
Analytics:
  - analytics/**/*
Analytics Base:
  - analyticsbase/**/*
Analytics Migration:
  - analyticsmigration/**/*
Analytics Sync:
  - analyticssync/**/*
Application:
  - application/**/*
Appstore:
  - appstore/**/*
Auditlog:
  - auditlog/**/*
Automation:
  - automation/**/*
Base:
  - base/**/*
Build:
  - buildscripts/**/*
Businessobject:
  - businessobject/**/*
Case:
  - case/**/*
Changestream:
  - changestream/**/*
Chat:
  - chat/**/*
Chat Worker:
  - chatworker/**/*
Common:
  - common/**/*
Community:
  - community/**/*
Connector:
  - connector/**/*
Dataset:
  - dataset/**/*
Digital Hub:
  - digitalhub/**/*
Documentparser:
  - documentparser/**/*
Documentparser Model:
  - documentparsermodel/**/*
Event Subscription:
  - eventsubscription/**/*
Filetransfer Worker:
  - filetransferworker/**/*
Flow:
  - flow/**/*
Form:
  - form/**/*
Form Report:
  - formreport/**/*
Gateway:
  - gateway/**/*
GCM:
  - gcm/**/*
Indexmanger:
  - indexmanger/**/*
Integration:
  - integration/**/*
Lowcode:
  - lowcode/**/*
Marketplace:
  - marketplace/**/*
Metadata:
  - metadata/**/*
Notification:
  - notification/**/*
Platform Base:
  - platformbase/**/*
Portal:
  - portal/**/*
Post:
  - post/**/*
Process:
  - process/**/*
Process Report:
  - processreport/**/*
Project:
  - project/**/*
Project Report:
  - projectreport/**/*
Report Base:
  - reportbase/**/*
Route:
  - route/**/*
Scheduler:
  - scheduler/**/*
Search:
  - search/**/*
Team:
  - team/**/*
Upload:
  - upload/**/*
User:
  - user/**/*
Workflow Woker:
  - workflowwoker/**/*
Dockerfile:
  - "Dockerfile*"
Jenkinsfile:
  - "Jenkinsfile*"
Test Case:
  - "**/tests/**/*"
